import numpy as np
import matplotlib.pyplot as plt
import json
import os
from PIL import Image
import base64
import ast # needed to convert string representation of list to actual list
import requests
from tenacity import retry, stop_after_attempt, wait_exponential

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')


# Process the food recipe data
with open("data/food_recipes.json", "r") as f:
    recipe_data = json.load(f)


# Define the Vision LLM With LLama
def vision_llm(system_msg, prompt_txt, image_path):
    pass


# Design The prompt for LLM
def image_caption_prompt_template(food_name):
    ### Step 3.1: Design the prompts
    image_caption_system_msg = (
        "You are a careful food image captioning assistant. "
        "Describe only what is clearly visible in the food image. "
        "Focus on the named dish, visible ingredients, cooking style, presentation, portion size, texture, and color. "
        "Do not guess or invent ingredients, recipe steps, cuisine, taste, or nutrition. "
        "Keep the caption concise, factual, and suitable for JSON."
    )
    image_caption_prompt_txt = (
        f"Generate a concise caption for the food image of '{food_name}'. "
        "Use only visible visual details. "
        "If something is unclear, do not speculate."
    )
    return image_caption_system_msg, image_caption_prompt_txt


# Caption all image and Augment the data
for i in range(len(recipe_data)):
    if (i+1)%20 == 0:
        print(f'{i+1} out of {len(recipe_data)} is done')
    food_name = recipe_data[i].get("name", recipe_data[i].get("title", "Unknown Dish"))
    image_path = os.path.join("synthetic_recipe_images", f"recipe{i+1}.png")

    # Generate the prompt for the LLM
    system_msg, prompt_txt = image_caption_prompt_template(food_name)

    # Call the Vision LLM to generate the caption
    response = vision_llm(system_msg, prompt_txt, image_path)

    # Augment the recipe data with the generated caption
    recipe_data[i]["image_description"] = response

# Save the augmented data to a new file
filename = 'augmented_food_recipe.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(recipe_data, f, indent=4)


# PREPROCESS THE USER HISTORY

# Load the data
user_review_data = json.load(open(r"AI-Powered-MultiModal-Recommendation-System\data\Synthetic-User-Reviews.json", "r"))

# image in the user_review_data is string representaion of list

# convert the string representation of list to actual list
for i in range(len(user_review_data)):
    # multiple images are stored as a string representation of a list in the 'image' field, so we need to convert it to an actual list
    for item in user_review_data[i]['image']:
        if isinstance(item, str):
            try:
                user_review_data[i]['image'] = ast.literal_eval(user_review_data[i]['image'])
            except (ValueError, SyntaxError):
                user_review_data[i]['image'] = []


# Prompt template: caption the images with the context of the reviews
def review_context_image_caption_prompt_template(reviews):
    # reviews: the written review content


    ### Step 2.1: Design your prompts
    review_context_image_caption_system_msg = (
        "You are a culinary expert analyzing food images. "
        "Use the user review as context, but only describe what is supported by the image and the review. "
        "Focus on visible food items, presentation, ingredients, and style. "
        "Keep the caption concise and avoid unsupported guesses."
    )
    review_context_image_caption_prompt_txt = (
        f"Based on the following review context, generate a concise description of the food image: {reviews}. "
        "Make sure the caption matches the image and reflects the review details when relevant."
    )

    return review_context_image_caption_system_msg, review_context_image_caption_prompt_txt 

# Caption all images in the user reviews and augment the data
@retry(stop=stop_after_attempt(10), wait=wait_exponential(multiplier=1, min=2, max=10))
def get_data_with_retry(url):
    response = requests.get(url, timeout=5)  # Set a timeout for the request
    response.raise_for_status()  # Raise an error for bad responses
    return response.json()

for i in range(len(user_review_data)):
    if (i+1)%20 == 0:
        print(f'{i+1} out of {len(user_review_data)} is done')
    review_images = user_review_data[i].get("images", [])

    review_image_caption = []
    if len(review_images) > 0:
        for image_url in review_images:
            try:
                image_data = get_data_with_retry(image_url)
            except requests.exceptions.RequestException as e:
                print(f"Failed to fetch image from {image_url}: {e}")
                continue
            image = image_data.content

            with open("review_image_placeholder.jpg", "wb") as f:
                f.write(image)

            # Generate the prompt for the LLM
            system_msg, prompt_txt = review_context_image_caption_prompt_template(user_review_data[i].get("review", ""))

            # Call the Vision LLM to generate the caption
            response = vision_llm(system_msg, prompt_txt, "review_image_placeholder.jpg")

            # Append the generated caption to the list
            review_image_caption.append(response)
    print("All done")

filename = 'augmented_user_review.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(user_review_data, f, indent=4)