"""fix refresh_tokens timezone

Revision ID: 65b9f0789708
Revises: 0003
Create Date: 2026-09-12 17:53:06.899099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b9f0789708'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.create_index(op.f('ix_conversation_history_id'), 'conversation_history', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    op.create_foreign_key(None, 'reviews', 'restaurants', ['restaurant_id'], ['id'])
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_feedback_id'), 'user_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_user_memory_summaries_id'), 'user_memory_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # NOTE: removed an autogenerated `alter_column('users', 'hashed_password',
    # nullable=False)` here. It was a false diff caused by db_models.py's
    # User.hashed_password never being updated to nullable=True after
    # 0002_google_oauth.py made it nullable on the actual DB. Applying it
    # would either fail outright (existing google-only rows already have
    # NULL there) or silently break every future Google-only signup.
    # Email uniqueness below is unaffected — it's still enforced by the
    # separate `ix_users_email` unique index created in 0001; this just
    # drops the redundant named constraint.
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_memory_summaries_id'), table_name='user_memory_summaries')
    op.drop_index(op.f('ix_user_feedback_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversation_history_id'), table_name='conversation_history')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###